import {
  UsersRound,
  GraduationCap,
  Mails,
  Megaphone,
  Calendar,
  Images,
  Clapperboard,
  Backpack,
  BookOpenText,
  NotebookText,
  AppWindow,
  BookUser,
} from "lucide-react";

const QuickActionData = [
  {
    id: 1,
    icon: UsersRound,
    title: "Siswa",
    description: "Tambah, edit, atau hapus data siswa",
    href: "/admin/siswa",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 2,
    icon: GraduationCap,
    title: "Guru",
    description: "Tambah, edit, atau hapus data guru",
    href: "/admin/guru",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 3,
    icon: Mails,
    title: "Berita",
    description: "Tulis dan publikasikan berita baru",
    href: "/admin/berita",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 4,
    icon: Megaphone,
    title: "Pengumuman",
    description: "Buat pengumuman penting untuk sekolah",
    href: "/admin/pengumuman",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 5,
    icon: Calendar,
    title: "Jadwal Kegiatan",
    description: "Atur jadwal dan kegiatan sekolah",
    href: "/admin/jadwal",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 6,
    icon: Images,
    title: "Galeri",
    description: "Upload dan kelola foto galeri",
    href: "/admin/galeri",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 7,
    icon: Clapperboard,
    title: "Ekstrakurikuler",
    description: "Atur ekstrakurikuler sekolah",
    href: "/admin/ekstrakurikuler",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 8,
    icon: Backpack,
    title: "Outing Class",
    description: "Atur outing class sekolah",
    href: "/admin/outing-class",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 9,
    icon: BookOpenText,
    title: "Pendaftaran",
    description: "Kelola informasi pendaftaran",
    href: "/admin/informasi-pendaftaran",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 10,
    icon: NotebookText,
    title: "Persyaratan",
    description: "Atur persyaratan pendaftaran sekolah",
    href: "/admin/persyaratan",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 11,
    icon: AppWindow,
    title: "Daftar Online",
    description: "Lihat hasil pendaftaran online",
    href: "/admin/daftar-online",
    color: "bg-[var(--primary-color)]",
  },
  {
    id: 12,
    icon: BookUser,
    title: "Kontak",
    description: "Kelola informasi kontak sekolah",
    href: "/admin/kontak",
    color: "bg-[var(--primary-color)]",
  },
];

export default QuickActionData;
